### ISSUE TITLE
Code flow error

### ISSUE THREAD

**Issue by pocallaghan** [mrkhoa99/Ajax-Newsletter-Magento-Footer#1]
By replacing the `Mage::throwException` with adding the error message to an array object you change the flow of the function. Anything that previously skipped into the catch block now continues through and still calls subscribe on the subscriber model. You should leave the throw exceptions in place and add `$e->getMessage()` into the response array in the catch blocks.

**Comment by mrkhoa99** [comment]
Hi Peter, 

Thanks in advance! I have just fixed my code!
